#slf4j日志配置
logging:
  # 配置级别
  level:
    #分包配置级别，即不同的目录下可以使用不同的级别
    #com.sblueice.controller: debug
    root: info
#服务器配置
server:
  port: 8081
  servlet:
    context-path: /
  jetty:
    max-http-form-post-size: 128MB
spring:
  #数据库配置
  #datasource:
    #username: root
    #password: 660195
    #url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.cj.jdbc.Driver
  #ehcache缓存配置
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  #rabbitmq消息中间件配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  #redis缓存配置
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 1024
        max-wait: -1s
        max-idle: 200
  #JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  # 使用的环境配置
  profiles:
    active: dev
  # 文件上传
  mvc:
    hiddenmethod:
      filter:
        enabled: false
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
#Mapper文件扫描配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: SESSION
    cache-enabled: true
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_UUID
      table-underline: true
      where-strategy: NOT_EMPTY
      insert-strategy: NOT_EMPTY
      update-strategy: NOT_EMPTY
